name: Deploy Node.js project to Azure Function App

on: [push]

env:
  AZURE_FUNCTIONAPP_NAME: noce2-tictactoe-api # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "./backend" # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: "12.x"
  ResourceGroupName: tictactoe-playing-server
  ResourceGroupLocation: "uksouth" # set this to the node version to use (supports 8.x, 10.x, 12.x)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@master

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: "Setup Azure Creds"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Setup Resource Group"
        uses: Azure/CLI@v1
        with:
          inlineScript: |
            #!/bin/bash
            az group create --name ${{ env.ResourceGroupName }} --location ${{ env.ResourceGroupLocation }}
            echo "Azure resource group created"

      - name: "Deploy Infra Components"
        id: infradeploy
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ env.ResourceGroupName }}
          template: ./azuredeploy.json
          parameters: ./azuredeploy.parameters.json

      - name: "Resolve Backend Project Dependencies Using Npm"
        shell: bash
        working-directory: "./backend"
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: "Deploy Function App Code"
        uses: Azure/functions-action@v1
        id: codedeploy
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

      # Azure logout
      - name: logout
        run: |
          az logout
        if: always()
